# Generated by Django 4.2.7 on 2025-12-13 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_id', models.CharField(db_index=True, max_length=100)),
                ('month', models.CharField(db_index=True, help_text='Format: YYYY-MM', max_length=7)),
                ('people_helped', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('events_conducted', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('funds_utilized', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ngo_id', 'month'], name='reports_rep_ngo_id_2651eb_idx'), models.Index(fields=['month'], name='reports_rep_month_67cfb8_idx')],
                'unique_together': {('ngo_id', 'month')},
            },
        ),
    ]
